version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Database=jokesdb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - jokes-network

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jokesdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jokes-network

networks:
  jokes-network:
    driver: bridge

volumes:
  postgres-data: 