name: JokesAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test with coverage
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    
    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Badges'
    
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: CoverageReport
        path: coveragereport
    
    - name: Create coverage badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Coverage
        color: brightgreen
        path: '**/coverage.cobertura.xml'
        gist-filename: code-coverage.json
        gist-id: ${{ secrets.GIST_ID }}
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }} 